version: '3.9'

services:
  cube:
    build:
      context: ./cube
      dockerfile: Dockerfile
    hostname: cube
    restart: always
    ports:
      - "8081:8081"
    networks:
      - my-custom-network

  square:
    build:
      context: ./Square
      dockerfile: Dockerfile
    hostname: square
    restart: always
    ports:
      - "8082:8082"
    networks:
      - my-custom-network

  fibonacci:
    build:
      context: ./fibonacci
      dockerfile: Dockerfile
    hostname: fibonacci
    restart: always
    ports:
      - "8083:8083"
    networks:
      - my-custom-network

  front_end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8086:80"
    depends_on:
      - cube
      - square
      - fibonacci
    networks:
      - my-custom-network

networks:
  my-custom-network:
    driver: bridge