version: '3.9'

services:
  cube:
    build:
      context: /Users/shubhu/Desktop/Projects/calculator/cube
      dockerfile: /Users/shubhu/Desktop/Projects/calculator/cube/Dockerfile
    restart: always
    ports:
      - "8081:8081"

  square:
    build:
      context: /Users/shubhu/Desktop/Projects/calculator/Square
      dockerfile: /Users/shubhu/Desktop/Projects/calculator/Square/Dockerfile
    restart: always
    ports:
      - "8082:8082"

  fibonacci:
    build:
      context: /Users/shubhu/Desktop/Projects/calculator/fibonacci
      dockerfile: /Users/shubhu/Desktop/Projects/calculator/fibonacci/Dockerfile
    restart: always
    ports:
      - "8083:8083"

  front_end:
    build:
      context: /Users/shubhu/Desktop/Projects/calculator/front-end
      dockerfile: /Users/shubhu/Desktop/Projects/calculator/front-end/Dockerfile
    restart: always
    ports:
      - "8086:80"
    depends_on:
      - cube
      - square
      - fibonacci